// src/App.jsx

import React, { useEffect, useRef } from "react";
import Quill from "quill";

// IMPORTANT: We need to import Quill's CSS for the editor to look correct.
import "quill/dist/quill.snow.css";
import "./App.css";

function App() {
  // useRef is used to get a direct reference to the editor div.
  // This allows Quill to take control of it without React interfering.
  const editorRef = useRef(null);

  // useEffect runs after the component has been rendered to the screen.
  // The empty array [] at the end means it will only run ONCE.
  useEffect(() => {
    // If the editor div exists and hasn't been initialized yet...
    if (editorRef.current && !editorRef.current.quill) {
      // ...create a new Quill editor instance.
      const quill = new Quill(editorRef.current, {
        theme: "snow", // 'snow' is a clean, modern theme with a toolbar
        modules: {
          toolbar: [
            [{ header: [1, 2, 3, false] }],
            ["bold", "italic", "underline"],
            [{ list: "ordered" }, { list: "bullet" }],
            ["link", "image"],
            ["clean"],
          ],
        },
      });
      // Store the quill instance on the ref so we can access it later if needed
      editorRef.current.quill = quill;
    }
  }, []); // The empty array ensures this effect runs only once

  return (
    <div className="app-container">
      {/* The toolbar will be automatically generated by Quill inside this div
        because of the theme: 'snow' option.
        So we can remove the manual toolbar div for now.
      */}
      <div className="editor-container">
        {/* We attach the ref to this div. Quill will work its magic here. */}
        <div ref={editorRef} className="editor"></div>
      </div>
    </div>
  );
}

export default App;
